version: "2"

services:

    gaeloprocessing:
        image: salimkanoun/gaeloprocessing
        container_name: gaeloprocessing
        restart: unless-stopped
        ports: ["8001:8000"]
        volumes: ["D:/Code/Gaelo_Processing:/home/gaelo_processing:Z"]
        environment:
            TZ: "Europe/Paris"
            ORTHANC_PROTOCOL: 'http://'
            ORTHANC_ADDRESS: "orthanc"
            ORTHANC_PORT: "8042"
            ORTHANC_USERNAME: "salim"
            ORTHANC_PASSWORD: "salim"
            TENSORFLOW_SERVING_ADDRESS : 'tfserving'
            TENSORFLOW_SERVING_PORT : 8500

    orthanc:
        image: osimis/orthanc:21.5.1
        container_name: orthanc
        restart: unless-stopped
        ports: ["8042:8042"]
        volumes: ["orthanc:/var/lib/orthanc/db:Z"]
        environment:
            ORTHANC__NAME: "Orthanc"
            ORTHANC__DICOM_SERVER_ENABLED: "false"
            ORTHANC__DICOM_MODALITIES_IN_DATABASE: "true"
            ORTHANC__ORTHANC_PEERS_IN_DATABASE: "true"
            DICOM_WEB_PLUGIN_ENABLED: "true"
            OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
            PYTHON_PLUGIN_ENABLED: "true"
            TRANSFERS_PLUGIN_ENABLED: "true"
            WORKLISTS_PLUGIN_ENABLED: "true"
            ORTHANC__REGISTERED_USERS: |
                {"salim": "salim"}
            ORTHANC__DICOM_WEB__ENABLE: "true"
            ORTHANC__DICOM_WEB__ROOT: "/dicom-web/"
            ORTHANC__DICOM_WEB__ENABLEWADO: "true"
            ORTHANC__DICOM_WEB__WADOROOT: "/wado"
            ORTHANC__DICOM_WEB__SSL: "true"
            ORTHANC__DICOM_WEB__STUDIESMETADATA: "MainDicomTags"
            ORTHANC__DICOM_WEB__SERIESMETADATA: "Full"

    tfserving:
        image: tensorflow/serving
        ports: 
            - "8500:8500"
            - "8501:8501"
        volumes: ["D:/data_docker/model:/models/aquisition_field_model",
                    "D:/data_docker/model/pt_segmentation_model:/models/pt_segmentation_model"]
        environment:
            MODEL_NAME: "aquisition_field_model"
            MODEL_NAME: "pt_segmentation_model"


volumes:
        orthanc:
        gaeloprocessing:
